### ISSUE TITLE
Add include/exclude pattern for all SketchUp departments

### ISSUE THREAD

**Issue by thomthom** [SketchUp/rubocop-sketchup#60]
Make it easier to include/exclude SketchUp cops search paths. Real fix is to get it into RuboCop itself (#70) - but until then another solution is needed.

```yml
AllCops:
  SketchUp:
    SourcePath: src
    TargetSketchUpVersion: 2014
    Exclude:
    - ^profiling/
    - ^tests/
```

```yml
AllCops:
  SketchUp:
    SourcePath: src
    TargetSketchUpVersion: 2014
    Include:
    - ^src/
```
