### ISSUE TITLE
Add reference links to cops

### ISSUE THREAD

**Issue by thomthom** [SketchUp/rubocop-sketchup#62]
Create a MarkDown page with more details about each cop, which then can be used for references.

Question: Should this markdown be part of RuboCop repo? Or part of maybe the Wiki?

Example: https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L1047

```yml
Performance/StringReplacement:
  Description: >-
                  Use `tr` instead of `gsub` when you are replacing the same
                  number of characters. Use `delete` instead of `gsub` when
                  you are deleting characters.
  Reference: 'https://github.com/JuanitoFatas/fast-ruby#stringgsub-vs-stringtr-code'
  Enabled: true
```
