### ISSUE TITLE
Move target SketchUp version to Compatibility cop?

### ISSUE THREAD

**Issue by thomthom** [SketchUp/rubocop-sketchup#75]
At the moment the target SketchUp version is configured at the AllCops level:

```yml
AllCops:
  SketchUp:
    TargetSketchUpVersion: 2016 M1
```

But does it make more sense to have it configured at cop level?

```yml
SketchupSuggestions/Compatibility:
    TargetSketchUpVersion: 2016 M1
```

Is there any need for any other cop to access this config?
